#ifndef __CLEANER_HEADER_H__
#define __CLEANER_HEADER_H__

// I2C
#define CLEANER_DEFAULT_I2C_SDA 21
#define CLEANER_DEFAULT_I2C_SCL 22
#define CLEANER_DEFAULT_I2C2_SDA 32
#define CLEANER_DEFAULT_I2C2_SCL 33

// Battery input pinout
#define CLEANER_DEFAULT_BATTERY 35
#define CLEANER_DEFAULT_BATTERY_MIN_VALUE    0
#define CLEANER_DEFAULT_BATTERY_MAX_VALUE 4095

// IRF520 Fan pinout
#define CLEANER_DEFAULT_FAN 13
#define CLEANER_DEFAULT_FAN_CHANNEL 0

// Motor pinout
#define CLEANER_DEFAULT_MOTOR_A01 12
#define CLEANER_DEFAULT_MOTOR_A02 14

#define CLEANER_DEFAULT_MOTOR_B01 17
#define CLEANER_DEFAULT_MOTOR_B02 15

#define CLEANER_DEFAULT_MOTOR_A01_CHANNEL 1
#define CLEANER_DEFAULT_MOTOR_A02_CHANNEL 2

#define CLEANER_DEFAULT_MOTOR_B01_CHANNEL 3
#define CLEANER_DEFAULT_MOTOR_B02_CHANNEL 4

#define CLEANER_DEFAULT_MOTOR_PWM 100

// Ledc setting
#define CLEANER_DEFAULT_LEDC_FREQ 5000
#define CLEANER_DEFAULT_LEDC_RESOLUTION 8

// ESP32 mDNS
#define CLEANER_DEFAULT_MDNS "cleaner"

// ESP32 ap mode
#define CLEANER_DEFAULT_AP_SSID   "esp32"
#define CLEANER_DEFAULT_AP_PASSWD "12345678"

// ESP32 sta mode
#define CLEANER_DEFAULT_STA_SSID   "esp32"
#define CLEANER_DEFAULT_STA_PASSWD "12345678"

#endif